global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: sdjpa-spring-data-rest

replicaCount: 1

image:
  repository: @docker.repo@/@project.artifactId@
  tag: @project.version@

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

spring:
  profiles:
    active: mysql

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

mysql:
  database: bookdb

  port: 3306
  targetPort: 3306
  nodePort: 30306

  adminUser: bookadmin
  adminPassword: password

  user: bookuser
  password: password

  rootPassword: password

ingress:
  enabled: false