spring:
  application:
    name: sdjpa-spring-data-rest

  docker:
    compose:
      enabled: false
      stop:
        command: down

  data:
    rest:
      base-path: /api/v9

  datasource:
    url: jdbc:h2:mem:sdjpa-datarest-test-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password

  sql:
    init:
      schema-locations: classpath:h2-schema.sql
      data-locations: classpath:h2-data.sql
      mode: never

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.zalando.logbook: TRACE
    org.hibernate.orm.jdbc.bind: INFO

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      # Exclude HTML-related calls and specific endpoints that Logbook doesn't handle correctly
      - path: /actuator/health/**
      - path: /webjars/**
      - path: /web/**
      - path: /h2-console/**  # Exclude H2 console
      - path: /swagger-ui/**  # Exclude Swagger UI if used
      - path: /v3/api-docs/** # Exclude OpenAPI docs if used
      - path: /favicon.ico
      # Exclude HTML-related calls and web resources
      - path: /**/*.html
      - path: /**/*.css
      - path: /**/*.js
      - path: /**/*.png
      - path: /**/*.jpg
      - path: /**/*.jpeg
      - path: /**/*.gif
      - path: /**/*.ico
      - path: /**/favicon.ico
      - path: /**/webjars/**
      # Exclude other common web resources
      - path: /**/assets/**
      - path: /**/static/**
      - path: /**/public/**
      - path: /**/resources/**
      # Add more exclusions as needed

server:
  port: 8080
