apiVersion: v1
data:
  init.sql: |-
    DROP DATABASE IF EXISTS paymentdb;
    DROP USER IF EXISTS `paymentadmin`@`%`;
    DROP USER IF EXISTS `paymentuser`@`%`;
    CREATE DATABASE IF NOT EXISTS paymentdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS `paymentadmin`@`%` IDENTIFIED BY 'password';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
        CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `paymentdb`.* TO `paymentadmin`@`%`;
    CREATE USER IF NOT EXISTS `paymentuser`@`%` IDENTIFIED BY 'password';
    GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `paymentdb`.* TO `paymentuser`@`%`;
    FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-init-script
