### get all beers
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v9/beer
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=sdjpa-spring-data-rest

### get profile
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v9/profile/beer
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=sdjpa-spring-data-rest

### find all beers by name (IPA)
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v9/beer/search/findAllByBeerName?beerName=IPA&page=0&size=10
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=sdjpa-spring-data-rest

### find all beers by style (IPA)
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v9/beer/search/findAllByBeerStyle?beerStyle=IPA&page=0&size=10
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=sdjpa-spring-data-rest

### find all beers by name and style (IPA)
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v9/beer/search/findAllByBeerNameAndBeerStyle?beerName=IPA&beerStyle=IPA&page=0&size=10
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=sdjpa-spring-data-rest

### find beer by UPC
< scripts/traceparent.js
GET http://localhost:{{application-port}}/api/v9/beer/search/findByUpc?upc=0631234200036
Accept: application/json
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=sdjpa-spring-data-rest
