global:
  namespace: sdjpa-spring-data-rest

mysql:
  port: 3306
  targetPort: 3306
  nodePort: 30306
  
  database: "bookdb"

  adminUser: bookadmin
  adminPassword: password

  user: bookuser
  password: password

  rootPassword: password

mysqlImage:
  repository: mysql
  tag: "8.4.7"
  pullPolicy: IfNotPresent
