apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-template.fullname" . }}-mysql
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "application-template.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database