apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-template.fullname" . }}-mysql
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "application-template.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "application-template.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.4.5
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_LOG_CONSOLE
              value: "true"
          envFrom:
            - secretRef:
                name: {{ include "application-template.fullname" . }}-mysql-secrets
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.port }}
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          emptyDir: { }
        - name: mysql-init-script
          configMap:
            name: {{ include "application-template.fullname" . }}-mysql-init